from cc3d import CompuCellSetup
from CancerInvasionSteppables import ComprehensiveCancerInvasionSteppable

CompuCellSetup.register_steppable(steppable=ComprehensiveCancerInvasionSteppable(frequency=1))
CompuCellSetup.run()
